<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.4" />
    <PackageReference Include="Silk.NET.OpenAL" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BluKube.Contracts\BluKube.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="BluKube.Contracts" />
  </ItemGroup>

</Project>
